[general]
cc_max_requests=20

; Device state mappings
cc_available_devstate=AVAILABLE
cc_active_devstate=INUSE
cc_callingparty_devstate=INUSE
cc_calledparty_devstate=INUSE
cc_waitingparty_devstate=ONHOLD
cc_monitoring_devstate=BUSY