[settings]
ps_endpoints => mysql,asterisk,ps_endpoints
ps_auths => mysql,asterisk,ps_auths
ps_aors => mysql,asterisk,ps_aors
ps_contacts => mysql,asterisk,ps_contacts
ps_registrations => mysql,asterisk,ps_registrations
ps_domain_aliases => mysql,asterisk,ps_domain_aliases
ps_provider_dids => mysql,asterisk,ps_provider_dids

[mysql]
dbhost = 127.0.0.1
dbname = asterisk
dbuser = asterisk
dbpass = f3mb0yTw1nkyB@!!69
dbport = 3306
dbsocket =