[general]
dateformat=%F %T
queue_log = yes
rotatestrategy = rotate
logger_queue_limit = 1000

[logfiles]
; console => debug,verbose,notice,warning,error,security
; messages => debug,verbose,notice,warning,error,security
; debug => debug,verbose
; error => error,warning
; full => debug,verbose,notice,warning,error,security
; security => security
; sip.log => debug,verbose,notice,warning,error,security
; pjsip.log => debug,verbose,notice,warning,error,security
; rtp.log => debug,verbose,notice,warning,error
; dtmf.log => debug,verbose,notice,warning,error
console => warning,error
messages => warning,error,security
sip.log => warning,error,security