[settings]
dbhost=127.0.0.1
dbname=asterisk
dbuser=asterisk
dbpass=f3mb0yTw1nkyB@!!69
dbport=3306
dbsock=/var/run/mysqld/mysqld.sock
connect_timeout=10

[ps_endpoints]
table=ps_endpoints
dbhost=127.0.0.1
dbname=asterisk
dbuser=asterisk
dbpass=f3mb0yTw1nkyB@!!69
dbport=3306
dbsock=/var/run/mysqld/mysqld.sock

[ps_aors]
table=ps_aors
dbhost=127.0.0.1
dbname=asterisk
dbuser=asterisk
dbpass=f3mb0yTw1nkyB@!!69
dbport=3306
dbsock=/var/run/mysqld/mysqld.sock

[ps_auths]
table=ps_auths
dbhost=127.0.0.1
dbname=asterisk
dbuser=asterisk
dbpass=f3mb0yTw1nkyB@!!69
dbport=3306
dbsock=/var/run/mysqld/mysqld.sock

[ps_contacts]
table=ps_contacts
dbhost=127.0.0.1
dbname=asterisk
dbuser=asterisk
dbpass=f3mb0yTw1nkyB@!!69
dbport=3306
dbsock=/var/run/mysqld/mysqld.sock

[ps_mwi]
table=ps_endpoints
dbhost=127.0.0.1
dbname=asterisk
dbuser=asterisk
dbpass=f3mb0yTw1nkyB@!!69
dbport=3306
dbsock=/var/run/mysqld/mysqld.sock
