[general]
dbhost = 127.0.0.1
dbname = asterisk
dbuser = asterisk
dbpass = f3mb0yTw1nkyB@!!69
dbport = 3306
requirements=warn
connect_timeout=10
ssl = false
charset = utf8
debug = 1

[asterisk]
dbhost = 127.0.0.1
dbname = asterisk
dbuser = asterisk
dbpass = f3mb0yTw1nkyB@!!69
dbport = 3306
requirements=warn
connect_timeout=10
ssl = false
charset = utf8