[res_pjsip]
transport=config,pjsip.conf,criteria=type=transport
endpoint=realtime,ps_endpoints
auth=realtime,ps_auths
aor=realtime,ps_aors

[res_pjsip_endpoint_identifier_ip]
identify=realtime,ps_domain_aliases

[res_pjsip_outbound_registration]
registration=realtime,ps_registrations

[res_pjsip_pubsub]
mwi=realtime,ps_endpoints

[res_pjsip_mwi]
message_summary=memory
subscription=realtime,ps_endpoints
body_generator=memory

[res_pjsip_mwi_body_generator]
validator=memory